### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by acabal** [michael-77/thomas-hardy_far-from-the-madding-crowd#1]
Re. the illustration can you convert the text to paths and ensure that there are no groupings or transforms in the image? You can do this by opening it in Inkscape and using the text to path command.

Also make sure there is no "height" attribute on the `<svg>` element. We only want a viewbox.

Then, use Inkscape to save it as an "optimized SVG" (not an "inkscape SVG"); then run `clean`.

When you open the SVG in a text editor, it should just be a series of `<path>` elements, with no transforms or styles.

Then, you need to put the illustration in a `<figure>` element, with accompanying style. See the semantics manual for copy and paste styling for illustrations. It is not necessary to give it a specific height in local.css; just make it a reasonable viewbox and the figure styling should take care of the rest.

- in local.css:

    -  `.signature` and `p[epub|type~="z3998:salutation"]` and `#chapter-34 blockquote header` do not need `font-style: normal`.

    - `.inscription" does not need `font-style: normal` or any of the margin styling. Its contents are already centered by virture of the `text-align` property.

-    The table in chapter-36.xhtml is better represented with `<table>` instead of `<blockquote>`. You can give the total row a top border; do not specify a border color. Also, use:

````css
    table{
    	margin: 1em auto;
    	font-variant-numeric: tabular-nums;
    }
````
See Walden for an example of tabular sums.

Then, you can remove the stray span around the total and instead target the total row with something like `table tr:last-child td:last-child`.

- It looks like you copied and pasted the long description from Wikipedia. This is not allowed because Wikipedia is a CC license which is not the same as CC0. Your long description must be completely original. So, please rewrite it in your own words.

**Comment by michael-77** [comment]
> Also make sure there is no "height" attribute on the `<svg>` element. We only want a viewbox.
> It is not necessary to give it a specific height in local.css; just make it a reasonable viewbox and the figure styling should take care of the rest.

Struggling here - if there is viewbox only on the svg element without any reference to a height in the svg or in local.css then the image is expanding to full width (with scaling height).  

I had a look in Moby Dick for reference (as it has an svg character) and it uses a css approach with height: ...em .

I've made all the other changes (5bda5c0, 49e458e) and checked them all in but would appreciate some input on getting the svg to work (156a131) without specifying a height.

Thanks

**Comment by acabal** [comment]
OK, I think I misspoke. You can style it using CSS then. But, the actual SVG source should still only have a viewbox.

**Comment by michael-77** [comment]
That should be all the issues resolved now (hopefully)

**Comment by acabal** [comment]
Excellent, thanks!
